"""
Phase 3 — script stage integration tests.

The one the plan asks for by name: a job whose user has NO provider keys
configured must leave job_logs rows that name each provider and explain the
key is missing, plus one self-contained human-readable ERROR row — never a
raw exception, never a silent failure.
"""
import uuid

import pytest
import respx

from app.models.models import Job, JobLog, JobStatus, User
from app.niches.seed import seed_niche_profiles
from runner.llm_adapter import ANTHROPIC_MESSAGES_URL, GROQ_CHAT_URL, Provider, ScriptGenerationFailed
from runner.script_stage import ScriptStageError, run_script_stage
from tests.planted import PLANTED_API_KEY
from tests.test_script_adapter import ANTHROPIC_OK, ECHOING_ERROR, only


@pytest.fixture()
def db(db_session):
    seed_niche_profiles(db_session)
    return db_session


@pytest.fixture()
def job(db):
    user = User(
        email=f"scriptstage_{uuid.uuid4().hex[:8]}@test.autotube.com",
        password_hash="x",
        full_name="Script Stage Test",
    )
    db.add(user)
    db.commit()
    job = Job(
        user_id=user.id,
        status=JobStatus.PENDING,
        config={"niche": "true_crime_narration", "topic": "The Dyatlov Pass incident", "format": "short"},
    )
    db.add(job)
    db.commit()
    return job


def logs_for(db, job):
    rows = db.query(JobLog).filter(JobLog.job_id == job.id).order_by(JobLog.id).all()
    return [(r.level, r.message) for r in rows]


class TestMissingKeys:
    def test_missing_keys_produce_named_human_readable_job_logs(self, db, job):
        """No keys configured → each provider named with a 'missing key' line,
        plus one self-contained ERROR row; job marked FAILED; no traceback."""
        with pytest.raises(ScriptGenerationFailed):
            run_script_stage(job, db)  # default key_lookup hits the (empty) vault

        logs = logs_for(db, job)
        warnings = [m for level, m in logs if level == "WARNING"]
        errors = [m for level, m in logs if level == "ERROR"]

        assert len(warnings) == 4
        for label in ("Anthropic (Claude)", "OpenAI", "Google Gemini", "Groq"):
            assert any(label in m and "no API key is saved" in m for m in warnings), label
        assert any("Settings" in m for m in warnings)  # tells the user where to fix it

        (error,) = errors
        assert error.startswith("Script generation failed")
        for label in ("Anthropic (Claude)", "OpenAI", "Google Gemini", "Groq"):
            assert label in error  # the ERROR row is self-contained

        all_text = " ".join(m for _, m in logs)
        assert "Traceback" not in all_text
        assert "ProviderKeyNotConfigured" not in all_text  # exception names stay internal

        db.refresh(job)
        assert job.status == JobStatus.FAILED

    @respx.mock
    def test_invalid_key_for_only_configured_provider(self, db, job):
        respx.post(GROQ_CHAT_URL).respond(401, json=ECHOING_ERROR)
        job.config = {**job.config, "script_provider_order": "groq"}
        db.commit()
        with pytest.raises(ScriptGenerationFailed):
            run_script_stage(job, db, key_lookup=only({Provider.groq}))
        logs = logs_for(db, job)
        assert any(level == "WARNING" and "Groq" in m and "rejected" in m and "invalid" in m
                   for level, m in logs)
        assert PLANTED_API_KEY not in " ".join(m for _, m in logs)


class TestHappyPath:
    @respx.mock
    def test_success_logs_provider_and_carries_needs_tts(self, db, job):
        respx.post(ANTHROPIC_MESSAGES_URL).respond(200, json=ANTHROPIC_OK)
        script = run_script_stage(job, db, key_lookup=only({Provider.anthropic}))
        assert script.provider is Provider.anthropic
        assert script.needs_tts is True  # true_crime_narration's flag, untouched
        logs = logs_for(db, job)
        assert any("Generating short script" in m and "True Crime" in m for _, m in logs)
        assert any("Script generated by anthropic" in m and "needs_tts=True" in m for _, m in logs)
        db.refresh(job)
        assert job.status == JobStatus.PENDING  # stage doesn't complete the job

    @respx.mock
    def test_config_fallback_order_is_respected(self, db, job):
        groq = respx.post(GROQ_CHAT_URL).respond(
            200, json={"choices": [{"message": {"content":
                "[SCENE]\nSPEECH: A short test scene for the order check.\nVISUAL: A desk\n[/SCENE]"}}]}
        )
        job.config = {**job.config, "script_provider_order": ["groq"]}
        db.commit()
        script = run_script_stage(job, db, key_lookup=only({Provider.groq}))
        assert groq.called and script.provider is Provider.groq


class TestBadConfig:
    def test_unknown_niche_fails_loudly_into_job_log(self, db, job):
        job.config = {**job.config, "niche": "does_not_exist"}
        db.commit()
        with pytest.raises(ScriptStageError):
            run_script_stage(job, db)
        logs = logs_for(db, job)
        assert any(level == "ERROR" and "does_not_exist" in m for level, m in logs)
        db.refresh(job)
        assert job.status == JobStatus.FAILED

    def test_missing_topic_fails_loudly(self, db, job):
        job.config = {"niche": "true_crime_narration"}
        db.commit()
        with pytest.raises(ScriptStageError):
            run_script_stage(job, db)
        assert any(level == "ERROR" and "topic" in m for level, m in logs_for(db, job))

    def test_bad_order_in_config_fails_loudly(self, db, job):
        job.config = {**job.config, "script_provider_order": "kling"}
        db.commit()
        with pytest.raises(ScriptStageError):
            run_script_stage(job, db)
        assert any(level == "ERROR" and "video provider" in m for level, m in logs_for(db, job))
