"""enterprise_upgrade_auth_and_subscriptions

Revision ID: 5b62f303a77c
Revises: add_celery_task_id_rev
Create Date: 2026-02-03 13:06:49.867723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b62f303a77c'
down_revision = 'add_celery_task_id_rev'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('channel_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_account_id', sa.Integer(), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['youtube_account_id'], ['youtube_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_stats_id'), 'channel_stats', ['id'], unique=False)
    op.create_table('video_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('watch_time_hours', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_stats_id'), 'video_stats', ['id'], unique=False)
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('videos_generated_this_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('usage_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.drop_column('users', 'username')
    op.add_column('videos', sa.Column('title', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_videos_youtube_id'), 'videos', ['youtube_id'], unique=False)
    op.add_column('youtube_accounts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('youtube_accounts', sa.Column('channel_id', sa.String(), nullable=True))
    op.add_column('youtube_accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_youtube_accounts_channel_id'), 'youtube_accounts', ['channel_id'], unique=True)
    op.create_foreign_key(None, 'youtube_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_youtube_accounts_channel_id'), table_name='youtube_accounts')
    op.drop_column('youtube_accounts', 'created_at')
    op.drop_column('youtube_accounts', 'channel_id')
    op.drop_column('youtube_accounts', 'user_id')
    op.drop_index(op.f('ix_videos_youtube_id'), table_name='videos')
    op.drop_column('videos', 'created_at')
    op.drop_column('videos', 'title')
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'usage_reset_at')
    op.drop_column('users', 'videos_generated_this_month')
    op.drop_column('users', 'subscription_ends_at')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    op.drop_index(op.f('ix_video_stats_id'), table_name='video_stats')
    op.drop_table('video_stats')
    op.drop_index(op.f('ix_channel_stats_id'), table_name='channel_stats')
    op.drop_table('channel_stats')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
