"""Add tokens revoked at

Revision ID: b243faaea1cc
Revises: 70be4291a240
Create Date: 2026-03-06 11:14:40.385530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b243faaea1cc'
down_revision = '70be4291a240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens_revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens_revoked_at')
    # ### end Alembic commands ###
