"""
Script stage: run script generation for a job and narrate it into job_logs.

This is the seam Phase 6 wires into the Actions pipeline. Everything a user
sees about script generation — which providers were tried, why each failed,
what succeeded — lands here as job_logs rows in our own wording. A failure
is a specific, human-readable ERROR row, never a traceback.
"""
from __future__ import annotations

import logging
import os
from typing import Sequence

from sqlalchemy.orm import Session

from app.models.models import Job, JobLog, JobStatus
from app.niches.accessor import get_niche_profile
from app.niches.schema import NicheProfileError
from runner.llm_adapter import (
    KeyLookup,
    Provider,
    ProviderAttempt,
    Script,
    ScriptGenerationFailed,
    generate_script,
)
from runner.provider_keys import ProviderKeyNotConfigured, load_provider_key

log = logging.getLogger(__name__)

ORDER_ENV_VAR = "SCRIPT_PROVIDER_ORDER"


class ScriptStageError(Exception):
    """The stage could not run (bad config, unknown niche). Message is job-log ready."""


def add_job_log(db: Session, job_id: int, message: str, level: str = "INFO") -> None:
    db.add(JobLog(job_id=job_id, message=message, level=level))
    db.commit()


def _fail(db: Session, job: Job, message: str) -> None:
    add_job_log(db, job.id, message, level="ERROR")
    job.status = JobStatus.FAILED
    db.commit()


def _log_attempts(db: Session, job: Job, attempts: Sequence[ProviderAttempt]) -> None:
    for attempt in attempts:
        add_job_log(db, job.id, attempt.message, level="WARNING")


def _vault_key_lookup(user_id: int, db: Session) -> KeyLookup:
    def lookup(provider: Provider):
        try:
            return load_provider_key(user_id, provider.value, db)
        except ProviderKeyNotConfigured:
            return None
        # Any other VaultDecryptError (private key missing/wrong, tampered
        # ciphertext) is an infrastructure fault, not a user mistake — let it
        # propagate to the runner's own error handling.
    return lookup


def run_script_stage(job: Job, db: Session, *, key_lookup: KeyLookup | None = None) -> Script:
    """Generate the script for `job`, writing job_logs as it goes.

    Returns the Script on success. On failure: writes WARNING rows per
    provider attempt plus one self-contained ERROR row, marks the job FAILED,
    and raises (ScriptStageError or ScriptGenerationFailed).
    """
    config = job.config or {}
    niche_id = config.get("niche")
    topic = config.get("topic")
    format = config.get("format", "short")
    if not niche_id or not topic:
        message = "Script stage cannot start: the job is missing its 'niche' or 'topic' setting."
        _fail(db, job, message)
        raise ScriptStageError(message)

    try:
        profile = get_niche_profile(niche_id, db)
    except NicheProfileError as exc:
        message = f"Script stage cannot start: {exc}"
        _fail(db, job, message)
        raise ScriptStageError(message)

    order = config.get("script_provider_order") or os.environ.get(ORDER_ENV_VAR) or None
    if key_lookup is None:
        key_lookup = _vault_key_lookup(job.user_id, db)

    add_job_log(
        db, job.id,
        f"Generating {format} script for niche '{profile.display_name}' on topic: {topic}",
    )
    try:
        script = generate_script(profile, topic, format, key_lookup=key_lookup, order=order)
    except ValueError as exc:  # bad configured fallback order
        message = f"Script stage cannot start: {exc}."
        _fail(db, job, message)
        raise ScriptStageError(message)
    except ScriptGenerationFailed as exc:
        _log_attempts(db, job, exc.attempts)
        _fail(db, job, exc.user_message)
        raise

    _log_attempts(db, job, script.failed_attempts)
    add_job_log(
        db, job.id,
        f"Script generated by {script.provider.value} ({script.model}): "
        f"{len(script.scenes)} scenes, ~{script.estimated_duration_seconds:.0f}s, "
        f"needs_tts={script.needs_tts}.",
    )
    return script
